# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
    case_sensitive: False
    use_lookup_tables: True
  - name: CRFEntityExtractor #RegexEntityExtractor CRFEntityExtractor(this is working better)
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb # this is to counter the misspelling words
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: False
    epochs: 100
  - name: EntitySynonymMapper
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
    - amount-of-money
    - time
    - number
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.2
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
